spring.application.name=shoe-management-backend

server.port=8080
server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://localhost:5432/shoe_fix
spring.datasource.username=postgres
spring.datasource.password=123456

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.pool-name=StudentPool
jwt.secret=mySuperSecretKeyForJwtThatIsAtLeast32CharactersLong123
jwt.expiration=86400000
ghtk.token=3PVrXGA8gbUa2e28oCbT55SeoImrqLxvbnpZlqx
ghtk.pick-province=Hà Nội
ghtk.pick-district=Sóc Sơn

vnpay.tmn-code=GPT7Z4F7
vnpay.hash-secret=S7TV92W31MZ65SRWGD62M6CC7IWXCQIC
vnpay.pay-url=https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
vnpay.return-url=http://localhost:5173/admin/pos/vnpay-return
vnpay.ipn-url=http://localhost:8080/api/v1/pos/vnpay/ipn
vnpay.pos-return-url=http://localhost:5173/admin/pos/vnpay-return
vnpay.online-return-url=http://localhost:5173/checkout/vnpay-return
